### ISSUE TITLE
Popover new prop: matchAnchorWidth

### ISSUE THREAD

**Issue by probablyup** [enigma-io/boundless#1]
The intent being that we'd measure the size of the anchor component and update the portalled popover container width to match on cDM, cDU, and window resize.

(default `false`)

This allows `Popover` to be used like a dropdown when you want the content to follow the size of the trigger button.

**Comment by newyork-anthonyng** [comment]
@probablyup If nobody has started on this, I'd like to work on this and submit a `PR` this weekend.

**Comment by probablyup** [comment]
@newyork-anthonyng Please feel free!

**Comment by newyork-anthonyng** [comment]
@probablyup I created a WIP PR #39.

I would love some feedback on this :)
