### ISSUE TITLE
Popover demo is broken in iOS

### ISSUE THREAD

**Issue by Haroenv** [enigma-io/boundless#26]
Hey!
First of all, his project looks really cool!

I noticed that the display of the buttons in the popover demo doesn't work in iOS 10

![img_1141](https://cloud.githubusercontent.com/assets/6270048/22738696/b86112fe-ee08-11e6-9cb5-5be25797b6de.PNG)

**Comment by yaycmyk** [comment]
Ah flexbox :) thanks I'll take a look tonight

**Comment by yaycmyk** [comment]
Should be fixed via https://github.com/enigma-io/boundless/commit/0faed043d1ad3f714c13b081edd32d3f8a82d542 when travis finishes rebuilding. Thanks for reporting!
